export interface StateData {
  slug: string
  name: string
  avgCost: string
  avgSavings: string
  payback: string
  incentives: string[]
  sunHours: string
  topCities: string[]
}

export const STATES: Record<string, StateData> = {
  alabama: {
    slug: "alabama",
    name: "Alabama",
    avgCost: "$11,000–$17,000",
    avgSavings: "$1,000–$1,400/yr",
    payback: "8–11 years",
    incentives: ["Federal 30% Tax Credit", "TVA Solar Solutions Program", "Net Metering (limited)"],
    sunHours: "4.5–5.5 peak hours/day",
    topCities: ["Birmingham", "Montgomery", "Huntsville", "Mobile", "Tuscaloosa"],
  },
  alaska: {
    slug: "alaska",
    name: "Alaska",
    avgCost: "$16,000–$26,000",
    avgSavings: "$800–$1,200/yr",
    payback: "14–20 years",
    incentives: ["Federal 30% Tax Credit", "Renewable Energy Grant Program", "Net Metering"],
    sunHours: "2.5–4.0 peak hours/day",
    topCities: ["Anchorage", "Fairbanks", "Juneau", "Sitka", "Ketchikan"],
  },
  arizona: {
    slug: "arizona",
    name: "Arizona",
    avgCost: "$11,000–$17,000",
    avgSavings: "$1,600–$2,100/yr",
    payback: "5–7 years",
    incentives: ["Federal 30% Tax Credit", "AZ Residential Tax Credit (25%)", "APS/SRP Rebates", "Sales Tax Exemption"],
    sunHours: "5.5–7.0 peak hours/day",
    topCities: ["Phoenix", "Tucson", "Mesa", "Scottsdale", "Chandler"],
  },
  arkansas: {
    slug: "arkansas",
    name: "Arkansas",
    avgCost: "$11,000–$17,000",
    avgSavings: "$900–$1,300/yr",
    payback: "9–12 years",
    incentives: ["Federal 30% Tax Credit", "Net Metering", "Property Tax Exemption"],
    sunHours: "4.5–5.5 peak hours/day",
    topCities: ["Little Rock", "Fort Smith", "Fayetteville", "Springdale", "Jonesboro"],
  },
  california: {
    slug: "california",
    name: "California",
    avgCost: "$14,000–$22,000",
    avgSavings: "$1,800–$2,400/yr",
    payback: "5–7 years",
    incentives: ["Federal 30% Tax Credit", "California Solar Initiative", "Net Energy Metering (NEM 3.0)", "Property Tax Exclusion"],
    sunHours: "5.5–6.5 peak hours/day",
    topCities: ["Los Angeles", "San Diego", "San Jose", "Sacramento", "Fresno"],
  },
  colorado: {
    slug: "colorado",
    name: "Colorado",
    avgCost: "$12,000–$20,000",
    avgSavings: "$1,400–$1,900/yr",
    payback: "6–8 years",
    incentives: ["Federal 30% Tax Credit", "Xcel Energy Rebate", "Colorado Energy Office Incentives", "Net Metering"],
    sunHours: "4.5–5.5 peak hours/day",
    topCities: ["Denver", "Colorado Springs", "Aurora", "Fort Collins", "Lakewood"],
  },
  connecticut: {
    slug: "connecticut",
    name: "Connecticut",
    avgCost: "$14,000–$22,000",
    avgSavings: "$1,500–$2,000/yr",
    payback: "7–9 years",
    incentives: ["Federal 30% Tax Credit", "CT Green Bank Incentive", "Zero Emission Renewable Energy Credit (ZREC)", "Sales Tax Exemption"],
    sunHours: "4.0–4.5 peak hours/day",
    topCities: ["Bridgeport", "New Haven", "Hartford", "Stamford", "Waterbury"],
  },
  delaware: {
    slug: "delaware",
    name: "Delaware",
    avgCost: "$13,000–$20,000",
    avgSavings: "$1,200–$1,700/yr",
    payback: "7–10 years",
    incentives: ["Federal 30% Tax Credit", "DE SREC Program", "Green Energy Program Grant", "Net Metering"],
    sunHours: "4.0–4.5 peak hours/day",
    topCities: ["Wilmington", "Dover", "Newark", "Middletown", "Smyrna"],
  },
  florida: {
    slug: "florida",
    name: "Florida",
    avgCost: "$11,000–$18,000",
    avgSavings: "$1,400–$1,900/yr",
    payback: "6–8 years",
    incentives: ["Federal 30% Tax Credit", "Florida Solar Energy Center Rebate", "Net Metering", "Sales Tax Exemption"],
    sunHours: "5.0–5.5 peak hours/day",
    topCities: ["Miami", "Orlando", "Tampa", "Jacksonville", "Fort Lauderdale"],
  },
  georgia: {
    slug: "georgia",
    name: "Georgia",
    avgCost: "$13,000–$20,000",
    avgSavings: "$1,200–$1,600/yr",
    payback: "8–10 years",
    incentives: ["Federal 30% Tax Credit", "Georgia Power Incentives", "Net Metering"],
    sunHours: "4.5–5.5 peak hours/day",
    topCities: ["Atlanta", "Augusta", "Columbus", "Savannah", "Athens"],
  },
  hawaii: {
    slug: "hawaii",
    name: "Hawaii",
    avgCost: "$14,000–$22,000",
    avgSavings: "$2,400–$3,200/yr",
    payback: "4–6 years",
    incentives: ["Federal 30% Tax Credit", "HI State Tax Credit (35%)", "Green Infrastructure Fee Waiver", "Net Metering"],
    sunHours: "5.5–6.5 peak hours/day",
    topCities: ["Honolulu", "Pearl City", "Hilo", "Kailua", "Waipahu"],
  },
  idaho: {
    slug: "idaho",
    name: "Idaho",
    avgCost: "$11,000–$18,000",
    avgSavings: "$900–$1,300/yr",
    payback: "9–12 years",
    incentives: ["Federal 30% Tax Credit", "Idaho State Tax Deduction (40% first year)", "Net Metering", "Property Tax Exemption"],
    sunHours: "4.5–5.5 peak hours/day",
    topCities: ["Boise", "Nampa", "Meridian", "Idaho Falls", "Pocatello"],
  },
  illinois: {
    slug: "illinois",
    name: "Illinois",
    avgCost: "$13,000–$20,000",
    avgSavings: "$1,200–$1,700/yr",
    payback: "7–10 years",
    incentives: ["Federal 30% Tax Credit", "Illinois Shines (SREC) Program", "Smart Inverter Rebate", "Net Metering"],
    sunHours: "4.0–5.0 peak hours/day",
    topCities: ["Chicago", "Aurora", "Rockford", "Joliet", "Naperville"],
  },
  indiana: {
    slug: "indiana",
    name: "Indiana",
    avgCost: "$12,000–$18,000",
    avgSavings: "$1,000–$1,400/yr",
    payback: "9–12 years",
    incentives: ["Federal 30% Tax Credit", "Net Metering", "Property Tax Deduction"],
    sunHours: "4.0–5.0 peak hours/day",
    topCities: ["Indianapolis", "Fort Wayne", "Evansville", "South Bend", "Carmel"],
  },
  iowa: {
    slug: "iowa",
    name: "Iowa",
    avgCost: "$12,000–$18,000",
    avgSavings: "$1,000–$1,400/yr",
    payback: "9–12 years",
    incentives: ["Federal 30% Tax Credit", "Iowa Solar Tax Credit (15%)", "Net Metering", "Property Tax Exemption"],
    sunHours: "4.0–5.0 peak hours/day",
    topCities: ["Des Moines", "Cedar Rapids", "Davenport", "Sioux City", "Iowa City"],
  },
  kansas: {
    slug: "kansas",
    name: "Kansas",
    avgCost: "$11,000–$17,000",
    avgSavings: "$1,100–$1,500/yr",
    payback: "8–11 years",
    incentives: ["Federal 30% Tax Credit", "Net Metering", "Property Tax Exemption"],
    sunHours: "4.5–5.5 peak hours/day",
    topCities: ["Wichita", "Overland Park", "Kansas City", "Topeka", "Olathe"],
  },
  kentucky: {
    slug: "kentucky",
    name: "Kentucky",
    avgCost: "$11,000–$17,000",
    avgSavings: "$900–$1,300/yr",
    payback: "9–12 years",
    incentives: ["Federal 30% Tax Credit", "Net Metering", "Database of State Incentives for Renewables (DSIRE)"],
    sunHours: "4.0–5.0 peak hours/day",
    topCities: ["Louisville", "Lexington", "Bowling Green", "Owensboro", "Covington"],
  },
  louisiana: {
    slug: "louisiana",
    name: "Louisiana",
    avgCost: "$11,000–$17,000",
    avgSavings: "$1,100–$1,500/yr",
    payback: "8–11 years",
    incentives: ["Federal 30% Tax Credit", "Net Metering", "Property Tax Exemption"],
    sunHours: "4.5–5.5 peak hours/day",
    topCities: ["New Orleans", "Baton Rouge", "Shreveport", "Lafayette", "Lake Charles"],
  },
  maine: {
    slug: "maine",
    name: "Maine",
    avgCost: "$13,000–$21,000",
    avgSavings: "$1,000–$1,500/yr",
    payback: "9–12 years",
    incentives: ["Federal 30% Tax Credit", "Efficiency Maine Rebate", "Net Energy Billing", "Property Tax Exemption"],
    sunHours: "3.5–4.5 peak hours/day",
    topCities: ["Portland", "Lewiston", "Bangor", "South Portland", "Auburn"],
  },
  maryland: {
    slug: "maryland",
    name: "Maryland",
    avgCost: "$13,000–$21,000",
    avgSavings: "$1,300–$1,800/yr",
    payback: "7–9 years",
    incentives: ["Federal 30% Tax Credit", "MD CleanEnergy Grant ($1,000)", "SREC Program", "Property Tax Credit", "Sales Tax Exemption"],
    sunHours: "4.0–4.5 peak hours/day",
    topCities: ["Baltimore", "Frederick", "Rockville", "Gaithersburg", "Bowie"],
  },
  massachusetts: {
    slug: "massachusetts",
    name: "Massachusetts",
    avgCost: "$14,000–$22,000",
    avgSavings: "$1,600–$2,100/yr",
    payback: "6–9 years",
    incentives: ["Federal 30% Tax Credit", "MA SMART Program", "Solar Tax Credit (15%)", "Net Metering", "Sales Tax Exemption"],
    sunHours: "4.0–4.5 peak hours/day",
    topCities: ["Boston", "Worcester", "Springfield", "Cambridge", "Lowell"],
  },
  michigan: {
    slug: "michigan",
    name: "Michigan",
    avgCost: "$13,000–$20,000",
    avgSavings: "$1,000–$1,500/yr",
    payback: "9–12 years",
    incentives: ["Federal 30% Tax Credit", "DTE/Consumers Energy Rebates", "Net Metering", "Property Tax Exemption"],
    sunHours: "3.5–4.5 peak hours/day",
    topCities: ["Detroit", "Grand Rapids", "Warren", "Sterling Heights", "Ann Arbor"],
  },
  minnesota: {
    slug: "minnesota",
    name: "Minnesota",
    avgCost: "$13,000–$20,000",
    avgSavings: "$1,000–$1,400/yr",
    payback: "9–12 years",
    incentives: ["Federal 30% Tax Credit", "Made in Minnesota Solar Incentive", "Xcel Energy Rebate", "Net Metering", "Property Tax Exemption"],
    sunHours: "3.5–4.5 peak hours/day",
    topCities: ["Minneapolis", "Saint Paul", "Rochester", "Duluth", "Bloomington"],
  },
  mississippi: {
    slug: "mississippi",
    name: "Mississippi",
    avgCost: "$11,000–$17,000",
    avgSavings: "$1,000–$1,400/yr",
    payback: "8–12 years",
    incentives: ["Federal 30% Tax Credit", "Net Metering", "TVA Solar Solutions"],
    sunHours: "4.5–5.5 peak hours/day",
    topCities: ["Jackson", "Gulfport", "Southaven", "Hattiesburg", "Biloxi"],
  },
  missouri: {
    slug: "missouri",
    name: "Missouri",
    avgCost: "$11,000–$18,000",
    avgSavings: "$1,000–$1,400/yr",
    payback: "9–12 years",
    incentives: ["Federal 30% Tax Credit", "Ameren/Evergy Rebates", "Net Metering", "Property Tax Exemption"],
    sunHours: "4.5–5.5 peak hours/day",
    topCities: ["Kansas City", "St. Louis", "Springfield", "Columbia", "Independence"],
  },
  montana: {
    slug: "montana",
    name: "Montana",
    avgCost: "$12,000–$19,000",
    avgSavings: "$900–$1,300/yr",
    payback: "9–13 years",
    incentives: ["Federal 30% Tax Credit", "MT Alternative Energy Revolving Loan Program", "Net Metering", "Property Tax Exemption"],
    sunHours: "4.0–5.5 peak hours/day",
    topCities: ["Billings", "Missoula", "Great Falls", "Bozeman", "Butte"],
  },
  nebraska: {
    slug: "nebraska",
    name: "Nebraska",
    avgCost: "$11,000–$18,000",
    avgSavings: "$1,000–$1,400/yr",
    payback: "9–12 years",
    incentives: ["Federal 30% Tax Credit", "LES/OPPD Rebates", "Net Metering", "Property Tax Exemption"],
    sunHours: "4.5–5.5 peak hours/day",
    topCities: ["Omaha", "Lincoln", "Bellevue", "Grand Island", "Kearney"],
  },
  nevada: {
    slug: "nevada",
    name: "Nevada",
    avgCost: "$12,000–$19,000",
    avgSavings: "$1,500–$2,000/yr",
    payback: "6–8 years",
    incentives: ["Federal 30% Tax Credit", "NV Energy Rebate Program", "Net Metering", "Property Tax Exemption"],
    sunHours: "5.5–6.5 peak hours/day",
    topCities: ["Las Vegas", "Henderson", "Reno", "North Las Vegas", "Sparks"],
  },
  "new-hampshire": {
    slug: "new-hampshire",
    name: "New Hampshire",
    avgCost: "$13,000–$21,000",
    avgSavings: "$1,100–$1,600/yr",
    payback: "8–11 years",
    incentives: ["Federal 30% Tax Credit", "NH Electric Co-op Rebate", "Net Metering", "Property Tax Exemption"],
    sunHours: "3.5–4.5 peak hours/day",
    topCities: ["Manchester", "Nashua", "Concord", "Derry", "Dover"],
  },
  "new-jersey": {
    slug: "new-jersey",
    name: "New Jersey",
    avgCost: "$13,000–$21,000",
    avgSavings: "$1,300–$1,800/yr",
    payback: "7–9 years",
    incentives: ["Federal 30% Tax Credit", "NJ Clean Energy Rebate", "SREC Program", "Sales Tax Exemption"],
    sunHours: "4.0–4.5 peak hours/day",
    topCities: ["Newark", "Jersey City", "Trenton", "Camden", "Edison"],
  },
  "new-mexico": {
    slug: "new-mexico",
    name: "New Mexico",
    avgCost: "$11,000–$18,000",
    avgSavings: "$1,400–$1,900/yr",
    payback: "6–8 years",
    incentives: ["Federal 30% Tax Credit", "NM Solar Market Development Tax Credit (10%)", "Net Metering", "Property Tax Exemption"],
    sunHours: "5.5–7.0 peak hours/day",
    topCities: ["Albuquerque", "Las Cruces", "Rio Rancho", "Santa Fe", "Roswell"],
  },
  "new-york": {
    slug: "new-york",
    name: "New York",
    avgCost: "$14,000–$23,000",
    avgSavings: "$1,100–$1,600/yr",
    payback: "8–11 years",
    incentives: ["Federal 30% Tax Credit", "NY-Sun Initiative ($0.20/W)", "NY Solar Tax Credit (25%)", "Net Metering"],
    sunHours: "3.5–4.5 peak hours/day",
    topCities: ["New York City", "Buffalo", "Rochester", "Albany", "Syracuse"],
  },
  "north-carolina": {
    slug: "north-carolina",
    name: "North Carolina",
    avgCost: "$12,000–$19,000",
    avgSavings: "$1,200–$1,700/yr",
    payback: "7–9 years",
    incentives: ["Federal 30% Tax Credit", "Duke Energy Rebate", "Net Metering", "Property Tax Exemption"],
    sunHours: "4.5–5.0 peak hours/day",
    topCities: ["Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem"],
  },
  "north-dakota": {
    slug: "north-dakota",
    name: "North Dakota",
    avgCost: "$12,000–$19,000",
    avgSavings: "$800–$1,200/yr",
    payback: "10–14 years",
    incentives: ["Federal 30% Tax Credit", "ND Income Tax Credit (3%)", "Net Metering", "Property Tax Exemption"],
    sunHours: "4.0–5.0 peak hours/day",
    topCities: ["Fargo", "Bismarck", "Grand Forks", "Minot", "West Fargo"],
  },
  ohio: {
    slug: "ohio",
    name: "Ohio",
    avgCost: "$12,000–$19,000",
    avgSavings: "$1,000–$1,500/yr",
    payback: "8–12 years",
    incentives: ["Federal 30% Tax Credit", "AEP/Duke Energy Rebates", "Net Metering", "Property Tax Exemption"],
    sunHours: "4.0–4.5 peak hours/day",
    topCities: ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron"],
  },
  oklahoma: {
    slug: "oklahoma",
    name: "Oklahoma",
    avgCost: "$11,000–$17,000",
    avgSavings: "$1,000–$1,400/yr",
    payback: "8–11 years",
    incentives: ["Federal 30% Tax Credit", "OG&E/PSO Rebates", "Net Metering", "Property Tax Exemption"],
    sunHours: "5.0–6.0 peak hours/day",
    topCities: ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow", "Lawton"],
  },
  oregon: {
    slug: "oregon",
    name: "Oregon",
    avgCost: "$12,000–$20,000",
    avgSavings: "$1,100–$1,600/yr",
    payback: "7–10 years",
    incentives: ["Federal 30% Tax Credit", "OR Residential Energy Tax Credit", "Energy Trust of Oregon Rebate", "Net Metering", "Property Tax Exemption"],
    sunHours: "4.0–5.5 peak hours/day",
    topCities: ["Portland", "Salem", "Eugene", "Gresham", "Hillsboro"],
  },
  pennsylvania: {
    slug: "pennsylvania",
    name: "Pennsylvania",
    avgCost: "$13,000–$21,000",
    avgSavings: "$1,100–$1,600/yr",
    payback: "8–11 years",
    incentives: ["Federal 30% Tax Credit", "PA SREC Program", "PPL/PECO Rebates", "Net Metering", "Sales Tax Exemption"],
    sunHours: "4.0–4.5 peak hours/day",
    topCities: ["Philadelphia", "Pittsburgh", "Allentown", "Erie", "Reading"],
  },
  "rhode-island": {
    slug: "rhode-island",
    name: "Rhode Island",
    avgCost: "$13,000–$21,000",
    avgSavings: "$1,400–$1,900/yr",
    payback: "7–9 years",
    incentives: ["Federal 30% Tax Credit", "RI Renewable Energy Growth Program", "Net Metering", "Property Tax Exemption", "Sales Tax Exemption"],
    sunHours: "4.0–4.5 peak hours/day",
    topCities: ["Providence", "Cranston", "Warwick", "Pawtucket", "East Providence"],
  },
  "south-carolina": {
    slug: "south-carolina",
    name: "South Carolina",
    avgCost: "$12,000–$19,000",
    avgSavings: "$1,100–$1,600/yr",
    payback: "7–10 years",
    incentives: ["Federal 30% Tax Credit", "SC Tax Credit (25%)", "Dominion/Duke Rebates", "Net Metering"],
    sunHours: "4.5–5.5 peak hours/day",
    topCities: ["Columbia", "Charleston", "North Charleston", "Mount Pleasant", "Rock Hill"],
  },
  "south-dakota": {
    slug: "south-dakota",
    name: "South Dakota",
    avgCost: "$12,000–$18,000",
    avgSavings: "$900–$1,300/yr",
    payback: "9–13 years",
    incentives: ["Federal 30% Tax Credit", "Net Metering", "Property Tax Exemption"],
    sunHours: "4.5–5.5 peak hours/day",
    topCities: ["Sioux Falls", "Rapid City", "Aberdeen", "Brookings", "Watertown"],
  },
  tennessee: {
    slug: "tennessee",
    name: "Tennessee",
    avgCost: "$11,000–$18,000",
    avgSavings: "$1,000–$1,400/yr",
    payback: "8–12 years",
    incentives: ["Federal 30% Tax Credit", "TVA Green Power Providers", "Net Metering", "Property Tax Exemption"],
    sunHours: "4.5–5.5 peak hours/day",
    topCities: ["Nashville", "Memphis", "Knoxville", "Chattanooga", "Clarksville"],
  },
  texas: {
    slug: "texas",
    name: "Texas",
    avgCost: "$12,000–$20,000",
    avgSavings: "$1,500–$2,000/yr",
    payback: "6–9 years",
    incentives: ["Federal 30% Tax Credit", "Property Tax Exemption", "Austin Energy Rebate", "Various Utility Rebates"],
    sunHours: "5.0–6.0 peak hours/day",
    topCities: ["Houston", "Dallas", "Austin", "San Antonio", "Fort Worth"],
  },
  utah: {
    slug: "utah",
    name: "Utah",
    avgCost: "$12,000–$19,000",
    avgSavings: "$1,200–$1,700/yr",
    payback: "7–10 years",
    incentives: ["Federal 30% Tax Credit", "UT Renewable Energy Systems Tax Credit (25%)", "Rocky Mountain Power Rebate", "Net Metering", "Sales Tax Exemption"],
    sunHours: "5.5–6.5 peak hours/day",
    topCities: ["Salt Lake City", "West Valley City", "Provo", "West Jordan", "Orem"],
  },
  vermont: {
    slug: "vermont",
    name: "Vermont",
    avgCost: "$13,000–$21,000",
    avgSavings: "$1,100–$1,600/yr",
    payback: "8–11 years",
    incentives: ["Federal 30% Tax Credit", "VT Clean Energy Development Fund", "Net Metering", "Sales Tax Exemption", "Property Tax Exemption"],
    sunHours: "3.5–4.5 peak hours/day",
    topCities: ["Burlington", "South Burlington", "Rutland", "Barre", "Montpelier"],
  },
  virginia: {
    slug: "virginia",
    name: "Virginia",
    avgCost: "$12,000–$20,000",
    avgSavings: "$1,100–$1,600/yr",
    payback: "7–10 years",
    incentives: ["Federal 30% Tax Credit", "Dominion Energy Rebate", "Net Metering", "Property Tax Exemption", "Sales Tax Exemption"],
    sunHours: "4.0–5.0 peak hours/day",
    topCities: ["Virginia Beach", "Norfolk", "Chesapeake", "Richmond", "Arlington"],
  },
  washington: {
    slug: "washington",
    name: "Washington",
    avgCost: "$13,000–$21,000",
    avgSavings: "$900–$1,300/yr",
    payback: "10–14 years",
    incentives: ["Federal 30% Tax Credit", "WA State Tax Exemption (Sales + B&O)", "Net Metering", "Property Tax Exemption"],
    sunHours: "3.5–5.0 peak hours/day",
    topCities: ["Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue"],
  },
  "west-virginia": {
    slug: "west-virginia",
    name: "West Virginia",
    avgCost: "$11,000–$17,000",
    avgSavings: "$800–$1,200/yr",
    payback: "10–14 years",
    incentives: ["Federal 30% Tax Credit", "Net Metering", "Property Tax Exemption"],
    sunHours: "4.0–4.5 peak hours/day",
    topCities: ["Charleston", "Huntington", "Morgantown", "Parkersburg", "Wheeling"],
  },
  wisconsin: {
    slug: "wisconsin",
    name: "Wisconsin",
    avgCost: "$13,000–$20,000",
    avgSavings: "$900–$1,400/yr",
    payback: "9–13 years",
    incentives: ["Federal 30% Tax Credit", "Focus on Energy Rebate", "MG&E/We Energies Rebates", "Net Metering", "Property Tax Exemption"],
    sunHours: "3.5–4.5 peak hours/day",
    topCities: ["Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine"],
  },
  wyoming: {
    slug: "wyoming",
    name: "Wyoming",
    avgCost: "$11,000–$18,000",
    avgSavings: "$900–$1,300/yr",
    payback: "9–13 years",
    incentives: ["Federal 30% Tax Credit", "Net Metering", "Property Tax Exemption"],
    sunHours: "5.0–6.0 peak hours/day",
    topCities: ["Cheyenne", "Casper", "Laramie", "Gillette", "Rock Springs"],
  },
}

export const STATE_SLUGS = Object.keys(STATES)

export function getStateBySlug(slug: string): StateData | undefined {
  return STATES[slug]
}
