export interface InsulationStateData {
  slug: string
  avgAtticCost: string
  avgAnnualSavings: string
  recommendedRValue: string
  topProject: string
  climateNote: string
  incentives: string[]
  payback: string
}

export const INSULATION_STATES: Record<string, InsulationStateData> = {
  alabama: {
    slug: "alabama",
    avgAtticCost: "$900–$2,200",
    avgAnnualSavings: "$200–$400/yr",
    recommendedRValue: "R-38 to R-60 (attic)",
    topProject: "Air sealing + blown-in attic insulation to R-49",
    climateNote: "Alabama's hot, humid summers mean air conditioning costs dominate. Attic insulation and air sealing prevent heat gain and reduce AC runtime. Moisture management and vapor barriers are critical in Alabama's humid climate.",
    incentives: ["Current insulation rebate eligibility should be verified", "Alabama Power energy efficiency rebates", "Weatherization Assistance Program (WAP) for income-qualified homeowners", "Federal 25C tax credit (verify current rules)"],
    payback: "3–6 years",
  },
  alaska: {
    slug: "alaska",
    avgAtticCost: "$1,500–$4,000",
    avgAnnualSavings: "$400–$900/yr",
    recommendedRValue: "R-60 to R-80 (attic)",
    topProject: "Dense-pack wall insulation + attic air sealing to R-60+",
    climateNote: "Alaska's extreme heating season makes insulation one of the highest-ROI home improvements. Super-insulation to R-60+ attic and R-21+ walls is standard for new construction. Weatherization funding is more available here than almost any state.",
    incentives: ["Current insulation rebate eligibility should be verified", "Alaska Housing Finance Corporation (AHFC) Home Energy Rebate Program", "Weatherization Assistance Program (income-qualified)", "AEA Alaska Warm Homes Program"],
    payback: "3–7 years",
  },
  arizona: {
    slug: "arizona",
    avgAtticCost: "$800–$2,000",
    avgAnnualSavings: "$250–$500/yr",
    recommendedRValue: "R-38 to R-49 (attic)",
    topProject: "Radiant barrier + blown-in attic insulation to R-49",
    climateNote: "In Arizona's intense heat, attic temperatures can exceed 160°F. Radiant barriers combined with blown-in insulation are the most effective combination. Air sealing around recessed lights and attic penetrations is critical.",
    incentives: ["Current insulation rebate eligibility should be verified", "APS Home Performance with ENERGY STAR rebates", "SRP Home Performance rebates", "Federal 25C insulation tax credit (verify current rules)"],
    payback: "3–6 years",
  },
  arkansas: {
    slug: "arkansas",
    avgAtticCost: "$900–$2,200",
    avgAnnualSavings: "$200–$420/yr",
    recommendedRValue: "R-38 to R-60 (attic)",
    topProject: "Attic air sealing + blown-in insulation to R-49",
    climateNote: "Arkansas has both hot summers and cold winters, making proper insulation valuable year-round. Blown-in cellulose or fiberglass attic insulation combined with air sealing delivers the best payback.",
    incentives: ["Current insulation rebate eligibility should be verified", "Entergy Arkansas Home Energy Improvement rebates", "Weatherization Assistance Program", "Federal 25C tax credit (verify current rules)"],
    payback: "4–7 years",
  },
  california: {
    slug: "california",
    avgAtticCost: "$1,200–$3,000",
    avgAnnualSavings: "$200–$500/yr",
    recommendedRValue: "R-30 to R-60 (varies by climate zone)",
    topProject: "Air sealing + blown-in attic upgrade per local Title 24 requirements",
    climateNote: "California has 16 climate zones — requirements vary widely. Coastal zones prioritize moderate insulation; inland and mountain zones need R-49 to R-60. Title 24 requires specific R-values for any alteration. TECH Clean California and utility rebates are available.",
    incentives: ["Current insulation rebate eligibility should be verified", "TECH Clean California rebates (up to $3,000 for whole-home)", "PG&E / SCE / SDG&E utility rebates", "PACE financing (CalFirst, Renovate America)"],
    payback: "4–9 years",
  },
  colorado: {
    slug: "colorado",
    avgAtticCost: "$1,000–$2,600",
    avgAnnualSavings: "$250–$550/yr",
    recommendedRValue: "R-49 to R-60 (attic)",
    topProject: "Attic air sealing + blown-in to R-60 before heating season",
    climateNote: "Colorado's cold, dry winters and high altitude mean heating costs are significant. Tight air sealing is especially important at altitude where stack effect drives large air leakage. Xcel Energy offers solid rebate programs.",
    incentives: ["Current insulation rebate eligibility should be verified", "Xcel Energy Home Efficiency Rebate (up to $300 for insulation)", "Colorado Energy Office weatherization programs", "Federal 25C tax credit (verify current rules)"],
    payback: "3–6 years",
  },
  connecticut: {
    slug: "connecticut",
    avgAtticCost: "$1,400–$3,200",
    avgAnnualSavings: "$300–$600/yr",
    recommendedRValue: "R-49 to R-60 (attic)",
    topProject: "Comprehensive air sealing + attic blown-in to R-60",
    climateNote: "Connecticut's cold winters and high energy costs make insulation one of the best investments. Eversource and UI offer strong rebate programs. Many homes have knob-and-tube wiring in attics — contractors must address this before adding insulation.",
    incentives: ["Current insulation rebate eligibility should be verified", "Eversource/UI Home Energy Solutions (up to $2,000 rebates)", "CT Green Bank on-bill financing", "Federal 25C tax credit (verify current rules)"],
    payback: "3–5 years",
  },
  delaware: {
    slug: "delaware",
    avgAtticCost: "$1,100–$2,600",
    avgAnnualSavings: "$250–$480/yr",
    recommendedRValue: "R-49 to R-60 (attic)",
    topProject: "Air sealing + blown-in attic insulation to R-49",
    climateNote: "Delaware's mixed climate (hot summers, cold winters) benefits from both heating and cooling insulation improvements. Delmarva Power offers rebates and Energize Delaware provides financing for qualifying homeowners.",
    incentives: ["Current insulation rebate eligibility should be verified", "Energize Delaware Home Performance Program", "Delmarva Power rebates", "Federal 25C tax credit (verify current rules)"],
    payback: "3–6 years",
  },
  florida: {
    slug: "florida",
    avgAtticCost: "$800–$2,000",
    avgAnnualSavings: "$200–$450/yr",
    recommendedRValue: "R-30 to R-49 (attic)",
    topProject: "Radiant barrier + blown-in attic insulation + air sealing",
    climateNote: "Florida's year-round heat means attic insulation focuses on cooling savings. Radiant barriers can cut attic temps by 30°F. Vapor barriers must be on the warm (exterior) side — reversing this is a common mistake causing mold in Florida's humid climate.",
    incentives: ["Current insulation rebate eligibility should be verified", "Duke Energy / FPL home energy programs", "PACE financing (Ygrene, Renew Financial)", "Federal 25C tax credit (verify current rules)"],
    payback: "3–6 years",
  },
  georgia: {
    slug: "georgia",
    avgAtticCost: "$900–$2,200",
    avgAnnualSavings: "$220–$440/yr",
    recommendedRValue: "R-38 to R-60 (attic)",
    topProject: "Attic air sealing + blown-in to R-49",
    climateNote: "Georgia's hot, humid summers and mild winters mean cooling savings drive payback. Atlanta metro homes often have inadequate attic insulation from original construction. Georgia Power offers rebates for certified insulation improvements.",
    incentives: ["Current insulation rebate eligibility should be verified", "Georgia Power Home Energy Improvement rebates", "Weatherization Assistance Program (income-qualified)", "Federal 25C tax credit (verify current rules)"],
    payback: "3–6 years",
  },
  hawaii: {
    slug: "hawaii",
    avgAtticCost: "$1,200–$3,000",
    avgAnnualSavings: "$150–$350/yr",
    recommendedRValue: "R-19 to R-30 (attic, mild climate)",
    topProject: "Air sealing + reflective insulation for cooling",
    climateNote: "Hawaii's mild year-round climate means insulation ROI is lower than mainland states. Focus is on reducing cooling loads. Trade wind ventilation is often more effective than added insulation. Moisture management in high-humidity areas is critical.",
    incentives: ["Current insulation rebate eligibility should be verified", "Hawaiian Electric Home Energy Program", "State income tax credit for energy improvements", "Federal 25C tax credit (verify current rules)"],
    payback: "8–15 years",
  },
  idaho: {
    slug: "idaho",
    avgAtticCost: "$1,000–$2,400",
    avgAnnualSavings: "$280–$550/yr",
    recommendedRValue: "R-49 to R-60 (attic)",
    topProject: "Attic air sealing + blown-in to R-60",
    climateNote: "Idaho's cold winters and warm summers create year-round demand for insulation. Idaho Power and Rocky Mountain Power offer rebates. Mountain and northern Idaho homes often need R-60+ attic insulation.",
    incentives: ["Current insulation rebate eligibility should be verified", "Idaho Power Home Improvement Program rebates", "Rocky Mountain Power Home Performance rebates", "Federal 25C tax credit (verify current rules)"],
    payback: "3–6 years",
  },
  illinois: {
    slug: "illinois",
    avgAtticCost: "$1,100–$2,700",
    avgAnnualSavings: "$300–$600/yr",
    recommendedRValue: "R-49 to R-60 (attic)",
    topProject: "Comprehensive air sealing + attic blown-in to R-60",
    climateNote: "Illinois has harsh winters and hot summers. ComEd and Nicor Gas offer strong rebate programs. Chicago-area homes with older construction often have significant air leakage and under-insulated attics. Air sealing before insulating is critical.",
    incentives: ["Current insulation rebate eligibility should be verified", "ComEd/Nicor Gas Home Energy Efficiency rebates", "Illinois Home Weatherization Assistance Program (IHWAP)", "Federal 25C tax credit (verify current rules)"],
    payback: "3–5 years",
  },
  indiana: {
    slug: "indiana",
    avgAtticCost: "$1,000–$2,500",
    avgAnnualSavings: "$280–$550/yr",
    recommendedRValue: "R-49 to R-60 (attic)",
    topProject: "Air sealing + blown-in attic insulation to R-49",
    climateNote: "Indiana's cold winters make heating costs the primary driver. Duke Energy and AES Indiana offer rebates. Many Indiana homes have significant attic air leakage around HVAC penetrations, wiring, and plumbing.",
    incentives: ["Current insulation rebate eligibility should be verified", "Duke Energy Indiana energy efficiency rebates", "Indiana Housing & Community Development weatherization", "Federal 25C tax credit (verify current rules)"],
    payback: "3–6 years",
  },
  iowa: {
    slug: "iowa",
    avgAtticCost: "$1,000–$2,500",
    avgAnnualSavings: "$280–$580/yr",
    recommendedRValue: "R-49 to R-60 (attic)",
    topProject: "Air sealing + blown-in to R-60",
    climateNote: "Iowa's cold winters and hot summers make insulation improvements highly cost-effective. MidAmerican Energy and Alliant Energy offer solid rebate programs. Many older Iowa homes have only R-11 to R-19 in the attic.",
    incentives: ["Current insulation rebate eligibility should be verified", "MidAmerican Energy Home Weatherization rebates", "Alliant Energy Home Performance rebates", "Federal 25C tax credit (verify current rules)"],
    payback: "3–5 years",
  },
  kansas: {
    slug: "kansas",
    avgAtticCost: "$950–$2,300",
    avgAnnualSavings: "$260–$520/yr",
    recommendedRValue: "R-49 to R-60 (attic)",
    topProject: "Attic air sealing + blown-in insulation to R-49",
    climateNote: "Kansas has hot summers and cold winters with strong winds that increase air infiltration. Evergy and Kansas Gas Service offer rebates. Rim joist insulation and air sealing is especially important given Kansas's extreme temperatures.",
    incentives: ["Current insulation rebate eligibility should be verified", "Evergy energy efficiency rebates", "Kansas Gas Service weatherization programs", "Federal 25C tax credit (verify current rules)"],
    payback: "3–6 years",
  },
  kentucky: {
    slug: "kentucky",
    avgAtticCost: "$950–$2,300",
    avgAnnualSavings: "$250–$500/yr",
    recommendedRValue: "R-49 to R-60 (attic)",
    topProject: "Attic air sealing + blown-in insulation to R-49",
    climateNote: "Kentucky's mixed climate with both heating and cooling seasons makes insulation valuable year-round. LG&E and Kentucky Utilities offer rebates. Many older Kentucky homes are significantly under-insulated.",
    incentives: ["Current insulation rebate eligibility should be verified", "LG&E/KU Energy efficiency programs", "Kentucky Housing Corporation weatherization assistance", "Federal 25C tax credit (verify current rules)"],
    payback: "3–6 years",
  },
  louisiana: {
    slug: "louisiana",
    avgAtticCost: "$800–$2,000",
    avgAnnualSavings: "$200–$430/yr",
    recommendedRValue: "R-30 to R-49 (attic)",
    topProject: "Radiant barrier + blown-in attic insulation + air sealing",
    climateNote: "Louisiana's hot, extremely humid climate requires moisture-aware insulation strategies. Vapor barriers must be correctly placed. Spray foam is popular for crawl spaces and rim joists. Entergy Louisiana offers rebates for qualifying projects.",
    incentives: ["Current insulation rebate eligibility should be verified", "Entergy Louisiana home energy improvement rebates", "Weatherization Assistance Program (income-qualified)", "Federal 25C tax credit (verify current rules)"],
    payback: "3–6 years",
  },
  maine: {
    slug: "maine",
    avgAtticCost: "$1,400–$3,500",
    avgAnnualSavings: "$400–$800/yr",
    recommendedRValue: "R-60 to R-80 (attic)",
    topProject: "Comprehensive air sealing + attic blown-in to R-60+",
    climateNote: "Maine has one of the longest heating seasons in the contiguous US. Efficiency Maine provides strong rebates and technical assistance. Many older Maine homes have virtually no wall insulation and inadequate attic insulation.",
    incentives: ["Current insulation rebate eligibility should be verified", "Efficiency Maine Home Energy Savings Program (up to $3,500)", "Weatherization Assistance Program", "Federal 25C tax credit (verify current rules)"],
    payback: "2–5 years",
  },
  maryland: {
    slug: "maryland",
    avgAtticCost: "$1,100–$2,600",
    avgAnnualSavings: "$280–$560/yr",
    recommendedRValue: "R-49 to R-60 (attic)",
    topProject: "Air sealing + blown-in attic insulation to R-49",
    climateNote: "Maryland's mixed climate benefits from both heating and cooling insulation improvements. BGE and Pepco offer Home Performance rebates. Many older Baltimore and DC-suburb homes have significant attic air leakage.",
    incentives: ["Current insulation rebate eligibility should be verified", "BGE/Pepco/Delmarva Home Performance with ENERGY STAR", "EmPOWER Maryland program", "Federal 25C tax credit (verify current rules)"],
    payback: "3–6 years",
  },
  massachusetts: {
    slug: "massachusetts",
    avgAtticCost: "$1,400–$3,500",
    avgAnnualSavings: "$350–$700/yr",
    recommendedRValue: "R-49 to R-60 (attic)",
    topProject: "Comprehensive air sealing + attic blown-in to R-60",
    climateNote: "Massachusetts has some of the strongest insulation rebate programs in the US. Mass Save offers rebates covering up to 75–100% of insulation costs for income-qualified homeowners. Cold winters make payback periods short.",
    incentives: ["Current insulation rebate eligibility should be verified", "Mass Save rebates (up to 75–100% of project cost for income-qualified)", "HEAT Loan 0% financing", "Federal 25C tax credit (verify current rules)"],
    payback: "2–4 years",
  },
  michigan: {
    slug: "michigan",
    avgAtticCost: "$1,100–$2,700",
    avgAnnualSavings: "$300–$620/yr",
    recommendedRValue: "R-49 to R-60 (attic)",
    topProject: "Air sealing + blown-in to R-60",
    climateNote: "Michigan's long, cold winters make attic insulation highly cost-effective. DTE Energy and Consumers Energy offer solid rebate programs. Many Michigan homes have older fiberglass batts that have settled and lost R-value.",
    incentives: ["Current insulation rebate eligibility should be verified", "DTE Energy Home Performance rebates", "Consumers Energy Whole Home program", "Federal 25C tax credit (verify current rules)"],
    payback: "3–5 years",
  },
  minnesota: {
    slug: "minnesota",
    avgAtticCost: "$1,300–$3,200",
    avgAnnualSavings: "$350–$700/yr",
    recommendedRValue: "R-49 to R-60 (attic, ice dam prevention)",
    topProject: "Attic air sealing to prevent ice dams + blown-in to R-60",
    climateNote: "Minnesota's extreme cold and long heating season make insulation one of the best investments. Ice dams are a major concern — proper attic air sealing before adding insulation is critical. Xcel Energy and CenterPoint Energy offer rebates.",
    incentives: ["Current insulation rebate eligibility should be verified", "Xcel Energy Home Improvement Program rebates", "CenterPoint Energy rebates", "Federal 25C tax credit (verify current rules)"],
    payback: "2–5 years",
  },
  mississippi: {
    slug: "mississippi",
    avgAtticCost: "$800–$2,000",
    avgAnnualSavings: "$200–$400/yr",
    recommendedRValue: "R-38 to R-49 (attic)",
    topProject: "Air sealing + blown-in attic insulation to R-38",
    climateNote: "Mississippi's hot, humid summers mean cooling savings drive insulation payback. Moisture management is critical. Entergy Mississippi and Mississippi Power offer rebate programs for qualifying improvements.",
    incentives: ["Current insulation rebate eligibility should be verified", "Entergy Mississippi home energy rebates", "TVA EnergyRight programs (north Mississippi)", "Federal 25C tax credit (verify current rules)"],
    payback: "3–7 years",
  },
  missouri: {
    slug: "missouri",
    avgAtticCost: "$950–$2,300",
    avgAnnualSavings: "$260–$520/yr",
    recommendedRValue: "R-49 to R-60 (attic)",
    topProject: "Attic air sealing + blown-in insulation to R-49",
    climateNote: "Missouri's humid continental climate means both heating and cooling savings contribute to insulation ROI. Ameren Missouri and Spire Natural Gas offer rebate programs. Tornado-prone areas should ensure proper attic bracing with insulation improvements.",
    incentives: ["Current insulation rebate eligibility should be verified", "Ameren Missouri BillSaver rebates", "Spire Energy weatherization programs", "Federal 25C tax credit (verify current rules)"],
    payback: "3–6 years",
  },
  montana: {
    slug: "montana",
    avgAtticCost: "$1,100–$2,700",
    avgAnnualSavings: "$320–$650/yr",
    recommendedRValue: "R-49 to R-60 (attic)",
    topProject: "Air sealing + blown-in attic insulation to R-60",
    climateNote: "Montana's cold winters and high energy prices make insulation highly cost-effective. NorthWestern Energy offers rebates. Many Montana homes have crawl space moisture problems that should be addressed before wall insulation.",
    incentives: ["Current insulation rebate eligibility should be verified", "NorthWestern Energy weatherization rebates", "Big Sky Trust Fund weatherization assistance", "Federal 25C tax credit (verify current rules)"],
    payback: "3–6 years",
  },
  nebraska: {
    slug: "nebraska",
    avgAtticCost: "$950–$2,300",
    avgAnnualSavings: "$270–$540/yr",
    recommendedRValue: "R-49 to R-60 (attic)",
    topProject: "Attic air sealing + blown-in insulation to R-49",
    climateNote: "Nebraska's extreme temperature swings — hot summers and cold winters — make year-round insulation savings significant. OPPD and LES offer rebates in the Omaha-Lincoln metro area.",
    incentives: ["Current insulation rebate eligibility should be verified", "OPPD/LES home energy rebates", "Nebraska Energy Office weatherization programs", "Federal 25C tax credit (verify current rules)"],
    payback: "3–6 years",
  },
  nevada: {
    slug: "nevada",
    avgAtticCost: "$800–$2,000",
    avgAnnualSavings: "$200–$440/yr",
    recommendedRValue: "R-38 to R-49 (attic)",
    topProject: "Radiant barrier + blown-in attic insulation + air sealing",
    climateNote: "Nevada's desert heat makes attic insulation critical for cooling cost reduction. Attic temperatures can exceed 150°F in Las Vegas summers. NV Energy offers rebates for qualifying insulation improvements.",
    incentives: ["Current insulation rebate eligibility should be verified", "NV Energy Home Energy Assistance rebates", "Nevada Gas home energy programs", "Federal 25C tax credit (verify current rules)"],
    payback: "3–6 years",
  },
  "new-hampshire": {
    slug: "new-hampshire",
    avgAtticCost: "$1,300–$3,200",
    avgAnnualSavings: "$350–$700/yr",
    recommendedRValue: "R-49 to R-60 (attic)",
    topProject: "Comprehensive air sealing + attic blown-in to R-60",
    climateNote: "New Hampshire's cold winters make insulation one of the best investments. Eversource NH and Liberty Utilities offer rebates. Many older NH homes have uninsulated or under-insulated attics with significant air leakage.",
    incentives: ["Current insulation rebate eligibility should be verified", "Eversource NH Home Energy Audit & Rebates", "Liberty Utilities weatherization programs", "Federal 25C tax credit (verify current rules)"],
    payback: "2–5 years",
  },
  "new-jersey": {
    slug: "new-jersey",
    avgAtticCost: "$1,200–$3,000",
    avgAnnualSavings: "$300–$600/yr",
    recommendedRValue: "R-49 to R-60 (attic)",
    topProject: "Air sealing + blown-in attic insulation to R-49",
    climateNote: "New Jersey's mixed climate and high energy costs make insulation very cost-effective. NJ Clean Energy Program offers strong rebates. Many NJ homes are row houses or attached homes where party walls also benefit from insulation.",
    incentives: ["Current insulation rebate eligibility should be verified", "NJ Home Performance with ENERGY STAR (up to $4,000)", "JCP&L / PSEG / Elizabethtown Gas rebates", "Federal 25C tax credit (verify current rules)"],
    payback: "3–5 years",
  },
  "new-mexico": {
    slug: "new-mexico",
    avgAtticCost: "$900–$2,200",
    avgAnnualSavings: "$220–$450/yr",
    recommendedRValue: "R-49 to R-60 (attic)",
    topProject: "Air sealing + blown-in attic insulation to R-49",
    climateNote: "New Mexico has both hot summers and cold winters, especially at altitude. PNM and New Mexico Gas Company offer rebates. Adobe and older construction often lacks modern wall insulation.",
    incentives: ["Current insulation rebate eligibility should be verified", "PNM energy efficiency rebates", "New Mexico Gas Company weatherization programs", "Federal 25C tax credit (verify current rules)"],
    payback: "3–7 years",
  },
  "new-york": {
    slug: "new-york",
    avgAtticCost: "$1,300–$3,500",
    avgAnnualSavings: "$300–$650/yr",
    recommendedRValue: "R-49 to R-60 (attic)",
    topProject: "Comprehensive air sealing + attic blown-in to R-60",
    climateNote: "New York's cold winters, high energy costs, and strong utility programs make insulation one of the best investments. NY Green Bank and NYSERDA offer robust financing. NYC homes need specialized approaches for multi-family and brownstone buildings.",
    incentives: ["Current insulation rebate eligibility should be verified", "NYSERDA Home Performance with ENERGY STAR rebates", "Con Edison / National Grid home energy programs", "Federal 25C tax credit (verify current rules)"],
    payback: "2–5 years",
  },
  "north-carolina": {
    slug: "north-carolina",
    avgAtticCost: "$950–$2,300",
    avgAnnualSavings: "$240–$480/yr",
    recommendedRValue: "R-38 to R-60 (attic, varies by location)",
    topProject: "Attic air sealing + blown-in insulation to R-49",
    climateNote: "North Carolina's mixed climate benefits year-round. Duke Energy Progress and Duke Energy Carolinas offer solid rebate programs. Mountain homes (Asheville area) need more aggressive insulation than coastal plain.",
    incentives: ["Current insulation rebate eligibility should be verified", "Duke Energy Home Energy Improvement rebates", "NCSEA weatherization programs", "Federal 25C tax credit (verify current rules)"],
    payback: "3–6 years",
  },
  "north-dakota": {
    slug: "north-dakota",
    avgAtticCost: "$1,100–$2,700",
    avgAnnualSavings: "$350–$700/yr",
    recommendedRValue: "R-49 to R-60 (attic)",
    topProject: "Air sealing + blown-in attic insulation to R-60",
    climateNote: "North Dakota's extremely cold winters make insulation critical. MDU and Xcel Energy (in select areas) offer rebates. Wind-driven infiltration is severe — air sealing must address all penetrations and the attic perimeter.",
    incentives: ["Current insulation rebate eligibility should be verified", "MDU Resources energy efficiency programs", "North Dakota Weatherization Assistance Program", "Federal 25C tax credit (verify current rules)"],
    payback: "2–5 years",
  },
  ohio: {
    slug: "ohio",
    avgAtticCost: "$1,000–$2,500",
    avgAnnualSavings: "$280–$560/yr",
    recommendedRValue: "R-49 to R-60 (attic)",
    topProject: "Air sealing + blown-in attic insulation to R-49",
    climateNote: "Ohio's cold winters and humid summers make insulation valuable year-round. AEP Ohio and FirstEnergy offer rebates. Many older Ohio homes (Cleveland, Columbus, Cincinnati) have under-insulated attics with significant air leakage.",
    incentives: ["Current insulation rebate eligibility should be verified", "AEP Ohio / FirstEnergy home energy programs", "Ohio Development Services Agency weatherization", "Federal 25C tax credit (verify current rules)"],
    payback: "3–5 years",
  },
  oklahoma: {
    slug: "oklahoma",
    avgAtticCost: "$900–$2,200",
    avgAnnualSavings: "$240–$480/yr",
    recommendedRValue: "R-38 to R-49 (attic)",
    topProject: "Attic air sealing + blown-in insulation to R-38",
    climateNote: "Oklahoma's hot summers and cold winters make insulation beneficial year-round. OG&E and PSO offer rebates. Tornado-prone areas should ensure insulation doesn't interfere with proper attic ventilation.",
    incentives: ["Current insulation rebate eligibility should be verified", "OG&E home energy rebate programs", "PSO Smart Hours and efficiency rebates", "Federal 25C tax credit (verify current rules)"],
    payback: "3–6 years",
  },
  oregon: {
    slug: "oregon",
    avgAtticCost: "$1,000–$2,500",
    avgAnnualSavings: "$250–$520/yr",
    recommendedRValue: "R-49 to R-60 (attic)",
    topProject: "Air sealing + blown-in attic insulation to R-49",
    climateNote: "Oregon's mild, wet climate means moisture management is as important as thermal insulation. Portland-area homes benefit from R-49 attic insulation. Eastern Oregon's colder climate requires R-60. Oregon Energy Trust offers strong rebates.",
    incentives: ["Current insulation rebate eligibility should be verified", "Energy Trust of Oregon home insulation rebates (up to $1,200)", "Pacific Power / Portland General Electric rebates", "Federal 25C tax credit (verify current rules)"],
    payback: "3–7 years",
  },
  pennsylvania: {
    slug: "pennsylvania",
    avgAtticCost: "$1,100–$2,700",
    avgAnnualSavings: "$300–$600/yr",
    recommendedRValue: "R-49 to R-60 (attic)",
    topProject: "Comprehensive air sealing + attic blown-in to R-49",
    climateNote: "Pennsylvania's cold winters and hot summers make insulation very cost-effective. PECO and PPL offer rebates. Many Philadelphia rowhouses benefit from rim joist and basement wall insulation in addition to attic work.",
    incentives: ["Current insulation rebate eligibility should be verified", "PECO/PPL ENERGY STAR Home Performance rebates", "Peoples Natural Gas weatherization", "Federal 25C tax credit (verify current rules)"],
    payback: "3–5 years",
  },
  "rhode-island": {
    slug: "rhode-island",
    avgAtticCost: "$1,300–$3,200",
    avgAnnualSavings: "$320–$650/yr",
    recommendedRValue: "R-49 to R-60 (attic)",
    topProject: "Air sealing + blown-in attic insulation to R-60",
    climateNote: "Rhode Island's cold winters and high energy costs make insulation an excellent investment. National Grid RI offers strong rebates and financing. RI Energy has comprehensive Home Energy Savings programs.",
    incentives: ["Current insulation rebate eligibility should be verified", "National Grid RI Home Energy Savings rebates", "RI Energy weatherization programs", "Federal 25C tax credit (verify current rules)"],
    payback: "2–4 years",
  },
  "south-carolina": {
    slug: "south-carolina",
    avgAtticCost: "$900–$2,200",
    avgAnnualSavings: "$220–$450/yr",
    recommendedRValue: "R-38 to R-49 (attic)",
    topProject: "Attic air sealing + blown-in insulation to R-38",
    climateNote: "South Carolina's hot, humid summers make cooling savings the primary driver. Duke Energy Carolinas and Dominion Energy SC offer rebates. Crawl space encapsulation is particularly valuable in SC's humid climate.",
    incentives: ["Current insulation rebate eligibility should be verified", "Duke Energy Carolinas home energy programs", "Dominion Energy SC rebates", "Federal 25C tax credit (verify current rules)"],
    payback: "3–6 years",
  },
  "south-dakota": {
    slug: "south-dakota",
    avgAtticCost: "$1,000–$2,500",
    avgAnnualSavings: "$300–$600/yr",
    recommendedRValue: "R-49 to R-60 (attic)",
    topProject: "Attic air sealing + blown-in insulation to R-60",
    climateNote: "South Dakota's cold winters and hot summers create year-round insulation demand. MDU and Xcel Energy offer rebates. Wind-driven infiltration is a major issue — thorough air sealing is critical.",
    incentives: ["Current insulation rebate eligibility should be verified", "MDU Resources energy efficiency programs", "Xcel Energy rebates (select areas)", "Federal 25C tax credit (verify current rules)"],
    payback: "3–5 years",
  },
  tennessee: {
    slug: "tennessee",
    avgAtticCost: "$900–$2,200",
    avgAnnualSavings: "$230–$460/yr",
    recommendedRValue: "R-38 to R-49 (attic)",
    topProject: "Attic air sealing + blown-in insulation to R-38",
    climateNote: "Tennessee's mixed climate benefits year-round from insulation. TVA EnergyRight offers strong rebates for qualifying homeowners. Many Tennessee homes have older fiberglass batts that have settled significantly.",
    incentives: ["Current insulation rebate eligibility should be verified", "TVA EnergyRight Home Uplift Program", "Nashville Electric Service and MLGW rebates", "Federal 25C tax credit (verify current rules)"],
    payback: "3–6 years",
  },
  texas: {
    slug: "texas",
    avgAtticCost: "$800–$2,000",
    avgAnnualSavings: "$200–$450/yr",
    recommendedRValue: "R-38 to R-49 (attic)",
    topProject: "Radiant barrier + blown-in attic insulation + air sealing",
    climateNote: "Texas summers are extreme — attic temperatures routinely exceed 150°F in DFW, Houston, and San Antonio. Radiant barriers combined with R-49 blown-in insulation are the most impactful combination. Oncor, AEP Texas, and CenterPoint offer rebates in some service areas.",
    incentives: ["Current insulation rebate eligibility should be verified", "Oncor Home Performance with ENERGY STAR rebates", "CenterPoint Energy home improvement programs", "Federal 25C tax credit (verify current rules)"],
    payback: "3–6 years",
  },
  utah: {
    slug: "utah",
    avgAtticCost: "$950–$2,400",
    avgAnnualSavings: "$270–$540/yr",
    recommendedRValue: "R-49 to R-60 (attic)",
    topProject: "Air sealing + blown-in attic insulation to R-49",
    climateNote: "Utah's cold winters (especially in Salt Lake City and higher elevations) and hot summers make insulation valuable year-round. Rocky Mountain Power offers rebates. Many Utah homes have uninsulated crawl spaces.",
    incentives: ["Current insulation rebate eligibility should be verified", "Rocky Mountain Power Home Performance rebates", "Questar Gas home energy programs", "Federal 25C tax credit (verify current rules)"],
    payback: "3–6 years",
  },
  vermont: {
    slug: "vermont",
    avgAtticCost: "$1,400–$3,500",
    avgAnnualSavings: "$400–$800/yr",
    recommendedRValue: "R-60 to R-80 (attic)",
    topProject: "Comprehensive air sealing + attic blown-in to R-60+",
    climateNote: "Vermont has one of the coldest heating climates in the lower 48. Efficiency Vermont offers some of the strongest insulation rebates in the country. Many Vermont homes have inadequate attic insulation and significant air leakage.",
    incentives: ["Current insulation rebate eligibility should be verified", "Efficiency Vermont Home Energy Loan and rebates", "Green Mountain Power Savings Plan", "Federal 25C tax credit (verify current rules)"],
    payback: "2–4 years",
  },
  virginia: {
    slug: "virginia",
    avgAtticCost: "$1,000–$2,500",
    avgAnnualSavings: "$260–$520/yr",
    recommendedRValue: "R-38 to R-60 (varies by region)",
    topProject: "Air sealing + blown-in attic insulation to R-49",
    climateNote: "Virginia's mixed climate (cold mountains to hot coastal plain) means insulation needs vary. Dominion Energy and Appalachian Power offer rebates. Northern Virginia homes near DC often have significant attic air leakage.",
    incentives: ["Current insulation rebate eligibility should be verified", "Dominion Energy Home Energy Rebate program", "Appalachian Power Home Performance rebates", "Federal 25C tax credit (verify current rules)"],
    payback: "3–6 years",
  },
  washington: {
    slug: "washington",
    avgAtticCost: "$1,000–$2,600",
    avgAnnualSavings: "$250–$500/yr",
    recommendedRValue: "R-49 to R-60 (attic)",
    topProject: "Air sealing + blown-in attic insulation to R-49",
    climateNote: "Western Washington's mild, wet climate means moisture management is critical. Eastern Washington has cold, dry winters requiring more aggressive insulation. Puget Sound Energy and Seattle City Light offer rebates.",
    incentives: ["Current insulation rebate eligibility should be verified", "Puget Sound Energy / Seattle City Light rebates", "Washington State Dept. of Commerce weatherization", "Federal 25C tax credit (verify current rules)"],
    payback: "3–7 years",
  },
  "west-virginia": {
    slug: "west-virginia",
    avgAtticCost: "$1,000–$2,500",
    avgAnnualSavings: "$280–$560/yr",
    recommendedRValue: "R-49 to R-60 (attic)",
    topProject: "Air sealing + blown-in attic insulation to R-49",
    climateNote: "West Virginia's cold, mountainous climate makes insulation highly cost-effective. Appalachian Power offers rebates. Many WV homes have older construction with minimal wall insulation and under-insulated attics.",
    incentives: ["Current insulation rebate eligibility should be verified", "Appalachian Power Home Performance programs", "WV Housing Development Fund weatherization", "Federal 25C tax credit (verify current rules)"],
    payback: "3–5 years",
  },
  wisconsin: {
    slug: "wisconsin",
    avgAtticCost: "$1,100–$2,700",
    avgAnnualSavings: "$320–$640/yr",
    recommendedRValue: "R-49 to R-60 (attic)",
    topProject: "Comprehensive air sealing + attic blown-in to R-60",
    climateNote: "Wisconsin's harsh winters make insulation among the best home investments. Focus on Energy offers strong rebates covering insulation and air sealing. Ice dam prevention requires thorough attic air sealing before adding blown-in.",
    incentives: ["Current insulation rebate eligibility should be verified", "Focus on Energy home performance rebates (up to $1,200)", "WE Energies / Wisconsin Gas home programs", "Federal 25C tax credit (verify current rules)"],
    payback: "2–5 years",
  },
  wyoming: {
    slug: "wyoming",
    avgAtticCost: "$1,000–$2,600",
    avgAnnualSavings: "$300–$620/yr",
    recommendedRValue: "R-49 to R-60 (attic)",
    topProject: "Air sealing + blown-in attic insulation to R-60",
    climateNote: "Wyoming's extreme cold and high winds make air sealing as important as insulation levels. Rocky Mountain Power serves most of the state. Many Wyoming homes have inadequate attic insulation and wind-driven infiltration.",
    incentives: ["Current insulation rebate eligibility should be verified", "Rocky Mountain Power Home Performance rebates", "Wyoming Energy Authority weatherization programs", "Federal 25C tax credit (verify current rules)"],
    payback: "3–5 years",
  },
}

export function getInsulationStateBySlug(slug: string): InsulationStateData | null {
  return INSULATION_STATES[slug] ?? null
}

export const INSULATION_STATE_SLUGS = Object.keys(INSULATION_STATES)
