export interface WindowsStateData {
  slug: string
  avgCost: string
  avgAnnualSavings: string
  recommendedType: string
  uFactor: string
  climateNote: string
  incentives: string[]
  payback: string
}

export const WINDOWS_STATES: Record<string, WindowsStateData> = {
  alabama: {
    slug: "alabama",
    avgCost: "$200–$500/window",
    avgAnnualSavings: "$100–$200/yr",
    recommendedType: "Double-pane Low-E with low SHGC (≤0.25)",
    uFactor: "≤0.30",
    climateNote: "Alabama's hot, humid summers demand windows with low solar heat gain coefficients (SHGC ≤ 0.25). Low-E coatings that block infrared heat are critical. Impact-resistant options are worth considering in coastal and southern Alabama.",
    incentives: ["Current window rebate eligibility should be verified", "Alabama Power energy efficiency programs", "Federal 25C tax credit (verify current IRS rules)", "ENERGY STAR Most Efficient certification may qualify for utility rebates"],
    payback: "10–20 years",
  },
  alaska: {
    slug: "alaska",
    avgCost: "$350–$800/window",
    avgAnnualSavings: "$200–$500/yr",
    recommendedType: "Triple-pane Low-E with argon/krypton fill",
    uFactor: "≤0.20",
    climateNote: "Alaska's extreme cold demands the highest-performance windows available. Triple-pane with krypton fill (U-factor ≤ 0.20) is standard. Fiberglass frames are preferred for their dimensional stability in extreme temperature swings. Condensation-resistant spacers are critical.",
    incentives: ["Current window rebate eligibility should be verified", "Alaska Housing Finance Corporation programs", "Weatherization Assistance Program (income-qualified)", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "5–12 years",
  },
  arizona: {
    slug: "arizona",
    avgCost: "$200–$480/window",
    avgAnnualSavings: "$100–$220/yr",
    recommendedType: "Double-pane Low-E with spectrally selective coating (low SHGC)",
    uFactor: "≤0.30",
    climateNote: "Arizona's intense solar radiation requires spectrally selective Low-E coatings that block heat while allowing visible light. Look for SHGC ≤ 0.22 in the Phoenix and Tucson areas. South and west-facing windows benefit most from solar control glass.",
    incentives: ["Current window rebate eligibility should be verified", "APS Cool Energy rebate programs", "SRP Home Performance rebates", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "10–18 years",
  },
  arkansas: {
    slug: "arkansas",
    avgCost: "$200–$480/window",
    avgAnnualSavings: "$100–$200/yr",
    recommendedType: "Double-pane Low-E with argon fill",
    uFactor: "≤0.30",
    climateNote: "Arkansas's mixed climate benefits from Low-E windows year-round. Hot summers require low SHGC on south and west exposures. Cold winters benefit from lower U-factors. Entergy Arkansas offers rebates for qualifying improvements.",
    incentives: ["Current window rebate eligibility should be verified", "Entergy Arkansas home energy programs", "Arkansas Natural Gas rebates", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "12–20 years",
  },
  california: {
    slug: "california",
    avgCost: "$250–$600/window",
    avgAnnualSavings: "$100–$250/yr",
    recommendedType: "Double-pane Low-E (climate zone varies — coastal vs. inland)",
    uFactor: "≤0.30 (varies by Title 24 climate zone)",
    climateNote: "California has 16 climate zones with different requirements under Title 24. Coastal areas prioritize moderate U-factor; inland hot climates need low SHGC. ENERGY STAR certification is required for most rebate programs. Wildfire-prone areas should consider tempered glass.",
    incentives: ["Current window rebate eligibility should be verified", "PG&E / SCE / SDG&E utility rebates (select programs)", "PACE financing (CalFirst, Renovate America)", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "10–20 years",
  },
  colorado: {
    slug: "colorado",
    avgCost: "$250–$550/window",
    avgAnnualSavings: "$150–$300/yr",
    recommendedType: "Double-pane Low-E with argon fill (triple-pane for mountain locations)",
    uFactor: "≤0.27",
    climateNote: "Colorado's cold winters and high altitude make low U-factor windows valuable. Denver area: double-pane Low-E with argon. Mountain towns (Aspen, Vail): triple-pane. Hail is a risk — ask about impact-resistant options from manufacturers.",
    incentives: ["Current window rebate eligibility should be verified", "Xcel Energy Home Efficiency rebates", "Colorado weatherization programs", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "8–15 years",
  },
  connecticut: {
    slug: "connecticut",
    avgCost: "$300–$650/window",
    avgAnnualSavings: "$150–$320/yr",
    recommendedType: "Double-pane Low-E with argon fill",
    uFactor: "≤0.27",
    climateNote: "Connecticut's cold winters and mixed summers make Low-E windows with argon fill the standard recommendation. Ice dam prevention is aided by well-insulated frames. Eversource and UI offer rebates for ENERGY STAR certified window replacements.",
    incentives: ["Current window rebate eligibility should be verified", "Eversource/UI Home Energy Solutions", "CT Green Bank financing options", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "8–15 years",
  },
  delaware: {
    slug: "delaware",
    avgCost: "$280–$600/window",
    avgAnnualSavings: "$130–$260/yr",
    recommendedType: "Double-pane Low-E with argon fill",
    uFactor: "≤0.30",
    climateNote: "Delaware's coastal location and mixed climate benefit from Low-E windows year-round. Moisture-resistant frames (vinyl or fiberglass) are preferred given coastal humidity. Energize Delaware offers financing for qualifying window replacements.",
    incentives: ["Current window rebate eligibility should be verified", "Energize Delaware Home Performance Program", "Delmarva Power energy efficiency rebates", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "10–18 years",
  },
  florida: {
    slug: "florida",
    avgCost: "$250–$600/window",
    avgAnnualSavings: "$100–$250/yr",
    recommendedType: "Impact-resistant Low-E with low SHGC (hurricane-rated)",
    uFactor: "≤0.35",
    climateNote: "Florida requires hurricane-rated windows in many counties (Miami-Dade, Broward). Impact-resistant Low-E windows with low SHGC double as storm protection and energy savers. South Florida requires Miami-Dade NOA approval or Florida Building Code impact certification.",
    incentives: ["Current window rebate eligibility should be verified", "Duke Energy / FPL energy efficiency programs", "PACE financing (Ygrene, Renew Financial) for impact windows", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "10–20 years",
  },
  georgia: {
    slug: "georgia",
    avgCost: "$220–$500/window",
    avgAnnualSavings: "$100–$220/yr",
    recommendedType: "Double-pane Low-E with low SHGC",
    uFactor: "≤0.30",
    climateNote: "Georgia's hot, humid summers prioritize windows with low solar heat gain. Atlanta-area homes benefit from Low-E with SHGC ≤ 0.25. Georgia Power offers rebates for qualifying ENERGY STAR certified replacements.",
    incentives: ["Current window rebate eligibility should be verified", "Georgia Power home energy rebates", "Municipal utility programs (Atlanta, Savannah)", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "12–20 years",
  },
  hawaii: {
    slug: "hawaii",
    avgCost: "$400–$900/window",
    avgAnnualSavings: "$80–$180/yr",
    recommendedType: "Double-pane Low-E with low SHGC and moisture-resistant frames",
    uFactor: "≤0.40",
    climateNote: "Hawaii's mild climate means window energy savings are modest. However, salt air corrosion is a major concern — fiberglass or vinyl frames far outlast aluminum in coastal environments. Trade wind ventilation through operable windows often replaces air conditioning.",
    incentives: ["Current window rebate eligibility should be verified", "Hawaiian Electric Home Energy programs", "State income tax credits for energy improvements", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "15–25 years",
  },
  idaho: {
    slug: "idaho",
    avgCost: "$250–$550/window",
    avgAnnualSavings: "$150–$300/yr",
    recommendedType: "Double-pane Low-E with argon fill (triple-pane for northern Idaho)",
    uFactor: "≤0.27",
    climateNote: "Idaho's cold winters demand low U-factor windows. Boise area: double-pane Low-E with argon. Northern Idaho and higher elevations: triple-pane. Idaho Power and Rocky Mountain Power offer rebates for qualifying replacements.",
    incentives: ["Current window rebate eligibility should be verified", "Idaho Power Home Improvement rebates", "Rocky Mountain Power Home Performance programs", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "8–15 years",
  },
  illinois: {
    slug: "illinois",
    avgCost: "$280–$600/window",
    avgAnnualSavings: "$150–$320/yr",
    recommendedType: "Double-pane Low-E with argon fill",
    uFactor: "≤0.27",
    climateNote: "Illinois has harsh winters and hot summers, making Low-E with argon the standard recommendation. Chicago-area homeowners should look for ENERGY STAR North-Central zone certification. Frame choice matters — vinyl and fiberglass resist thermal bridging better than aluminum.",
    incentives: ["Current window rebate eligibility should be verified", "ComEd/Nicor Gas Home Energy Efficiency programs", "Illinois Home Weatherization rebates", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "8–15 years",
  },
  indiana: {
    slug: "indiana",
    avgCost: "$260–$560/window",
    avgAnnualSavings: "$130–$280/yr",
    recommendedType: "Double-pane Low-E with argon fill",
    uFactor: "≤0.27",
    climateNote: "Indiana's cold winters make Low-E argon windows a solid investment. Duke Energy and AES Indiana offer rebates. Many Indiana homes still have original single-pane or early double-pane windows that lack Low-E coatings.",
    incentives: ["Current window rebate eligibility should be verified", "Duke Energy Indiana energy efficiency rebates", "Vectren/CenterPoint Energy Indiana programs", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "8–15 years",
  },
  iowa: {
    slug: "iowa",
    avgCost: "$260–$560/window",
    avgAnnualSavings: "$150–$320/yr",
    recommendedType: "Double-pane Low-E with argon fill",
    uFactor: "≤0.27",
    climateNote: "Iowa's cold winters and hot summers make energy-efficient windows valuable year-round. MidAmerican Energy and Alliant Energy offer rebates. Wind-driven rain is common — proper installation with flashing is critical.",
    incentives: ["Current window rebate eligibility should be verified", "MidAmerican Energy Home Weatherization rebates", "Alliant Energy Home Performance programs", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "8–14 years",
  },
  kansas: {
    slug: "kansas",
    avgCost: "$240–$540/window",
    avgAnnualSavings: "$130–$270/yr",
    recommendedType: "Double-pane Low-E with argon fill",
    uFactor: "≤0.30",
    climateNote: "Kansas has both hot summers and cold winters. Low-E with moderate SHGC (0.25–0.30) balances heating and cooling performance. Hail is a significant risk — impact-resistant glass is worth the premium in Kansas.",
    incentives: ["Current window rebate eligibility should be verified", "Evergy home energy rebates", "Kansas Gas Service programs", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "10–18 years",
  },
  kentucky: {
    slug: "kentucky",
    avgCost: "$240–$530/window",
    avgAnnualSavings: "$120–$250/yr",
    recommendedType: "Double-pane Low-E with argon fill",
    uFactor: "≤0.30",
    climateNote: "Kentucky's mixed climate benefits from Low-E windows year-round. LG&E and Kentucky Utilities offer rebates. Louisville and Lexington homes often have older aluminum-frame windows that can be upgraded for significant savings.",
    incentives: ["Current window rebate eligibility should be verified", "LG&E/KU home energy programs", "Kentucky Housing Corporation weatherization assistance", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "10–18 years",
  },
  louisiana: {
    slug: "louisiana",
    avgCost: "$230–$520/window",
    avgAnnualSavings: "$100–$220/yr",
    recommendedType: "Double-pane Low-E with very low SHGC (≤0.22)",
    uFactor: "≤0.35",
    climateNote: "Louisiana's extreme heat and humidity mean solar heat gain control is paramount. SHGC ≤ 0.22 dramatically reduces AC loads. In hurricane-risk areas, impact-resistant glass is strongly recommended. Salt air in coastal areas requires vinyl or fiberglass frames.",
    incentives: ["Current window rebate eligibility should be verified", "Entergy Louisiana home energy rebates", "PACE financing programs", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "12–20 years",
  },
  maine: {
    slug: "maine",
    avgCost: "$300–$700/window",
    avgAnnualSavings: "$200–$400/yr",
    recommendedType: "Triple-pane Low-E with argon fill (at minimum double-pane Low-E)",
    uFactor: "≤0.22",
    climateNote: "Maine's cold climate makes triple-pane windows a strong investment. Efficiency Maine offers rebates for high-performance windows. Storm windows over existing frames can also be cost-effective for older historic homes. Proper installation with air sealing maximizes performance.",
    incentives: ["Current window rebate eligibility should be verified", "Efficiency Maine Home Energy Savings Program", "Weatherization Assistance Program", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "6–12 years",
  },
  maryland: {
    slug: "maryland",
    avgCost: "$270–$580/window",
    avgAnnualSavings: "$130–$270/yr",
    recommendedType: "Double-pane Low-E with argon fill",
    uFactor: "≤0.27",
    climateNote: "Maryland's mixed climate benefits from Low-E windows year-round. BGE and Pepco offer Home Performance rebates. Baltimore rowhouses and DC-suburb homes often have older single or early double-pane windows with poor performance.",
    incentives: ["Current window rebate eligibility should be verified", "BGE/Pepco Home Performance with ENERGY STAR", "EmPOWER Maryland program", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "10–17 years",
  },
  massachusetts: {
    slug: "massachusetts",
    avgCost: "$300–$680/window",
    avgAnnualSavings: "$180–$360/yr",
    recommendedType: "Double-pane Low-E with argon fill (triple-pane for western MA)",
    uFactor: "≤0.27",
    climateNote: "Massachusetts has cold winters and some of the strongest utility rebate programs in the country. Mass Save offers rebates for ENERGY STAR certified windows. Boston-area homes with older windows often see payback under 10 years when combining rebates and energy savings.",
    incentives: ["Current window rebate eligibility should be verified", "Mass Save window rebates", "HEAT Loan 0% financing", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "7–14 years",
  },
  michigan: {
    slug: "michigan",
    avgCost: "$280–$620/window",
    avgAnnualSavings: "$160–$330/yr",
    recommendedType: "Double-pane Low-E with argon fill (triple-pane for upper peninsula)",
    uFactor: "≤0.27",
    climateNote: "Michigan's long, cold winters make energy-efficient windows a solid investment. DTE Energy and Consumers Energy offer rebates. Upper Peninsula homes need triple-pane windows for the extreme cold. Proper installation with air sealing is critical.",
    incentives: ["Current window rebate eligibility should be verified", "DTE Energy Home Performance rebates", "Consumers Energy Whole Home programs", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "7–13 years",
  },
  minnesota: {
    slug: "minnesota",
    avgCost: "$300–$680/window",
    avgAnnualSavings: "$180–$380/yr",
    recommendedType: "Triple-pane Low-E with argon fill",
    uFactor: "≤0.22",
    climateNote: "Minnesota's extreme cold makes triple-pane windows a strong investment. Xcel Energy and CenterPoint Energy offer rebates. Minneapolis-area homes that still have original single-pane or early double-pane windows can see significant savings. Condensation-resistant spacers and insulated frames are critical.",
    incentives: ["Current window rebate eligibility should be verified", "Xcel Energy Home Improvement rebates", "CenterPoint Energy efficiency programs", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "6–12 years",
  },
  mississippi: {
    slug: "mississippi",
    avgCost: "$220–$500/window",
    avgAnnualSavings: "$100–$210/yr",
    recommendedType: "Double-pane Low-E with low SHGC (≤0.25)",
    uFactor: "≤0.35",
    climateNote: "Mississippi's hot, humid climate means solar heat gain control is the top priority. Low SHGC glass dramatically reduces cooling loads. Coastal homes should consider impact-resistant options. Entergy Mississippi offers rebates for qualifying improvements.",
    incentives: ["Current window rebate eligibility should be verified", "Entergy Mississippi home energy rebates", "TVA EnergyRight (northern MS)", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "12–20 years",
  },
  missouri: {
    slug: "missouri",
    avgCost: "$240–$540/window",
    avgAnnualSavings: "$130–$270/yr",
    recommendedType: "Double-pane Low-E with argon fill",
    uFactor: "≤0.30",
    climateNote: "Missouri's hot summers and cold winters make Low-E with moderate SHGC (0.25–0.30) the best balance. Ameren Missouri and Spire Natural Gas offer rebates. Hail is a risk in Missouri — ask about impact-rated options.",
    incentives: ["Current window rebate eligibility should be verified", "Ameren Missouri BillSaver rebates", "Spire Energy weatherization programs", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "10–17 years",
  },
  montana: {
    slug: "montana",
    avgCost: "$280–$640/window",
    avgAnnualSavings: "$180–$380/yr",
    recommendedType: "Triple-pane Low-E with argon fill",
    uFactor: "≤0.22",
    climateNote: "Montana's cold winters and high altitude make triple-pane windows a strong investment. NorthWestern Energy offers rebates. Proper installation with air sealing is especially important given Montana's wind-driven infiltration.",
    incentives: ["Current window rebate eligibility should be verified", "NorthWestern Energy weatherization rebates", "Montana weatherization assistance programs", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "7–13 years",
  },
  nebraska: {
    slug: "nebraska",
    avgCost: "$250–$560/window",
    avgAnnualSavings: "$140–$290/yr",
    recommendedType: "Double-pane Low-E with argon fill",
    uFactor: "≤0.27",
    climateNote: "Nebraska's extreme temperature swings make energy-efficient windows valuable year-round. OPPD and LES offer rebates in Omaha and Lincoln. Hail and wind are significant hazards — impact-resistant glass is worth considering.",
    incentives: ["Current window rebate eligibility should be verified", "OPPD/LES home energy rebates", "Nebraska Energy Office programs", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "8–15 years",
  },
  nevada: {
    slug: "nevada",
    avgCost: "$220–$500/window",
    avgAnnualSavings: "$100–$230/yr",
    recommendedType: "Double-pane Low-E with spectrally selective coating and low SHGC",
    uFactor: "≤0.30",
    climateNote: "Nevada's extreme heat requires spectrally selective Low-E glass with SHGC ≤ 0.22 for Las Vegas and Reno summers. UV protection is also critical given Nevada's intense solar radiation. NV Energy offers rebates for qualifying improvements.",
    incentives: ["Current window rebate eligibility should be verified", "NV Energy Home Energy Assistance rebates", "Nevada Gas home energy programs", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "10–18 years",
  },
  "new-hampshire": {
    slug: "new-hampshire",
    avgCost: "$280–$650/window",
    avgAnnualSavings: "$180–$360/yr",
    recommendedType: "Double-pane Low-E with argon fill (triple-pane for northern NH)",
    uFactor: "≤0.27",
    climateNote: "New Hampshire's cold winters make energy-efficient windows a solid investment. Eversource NH and Liberty Utilities offer rebates. Northern NH and White Mountains area should consider triple-pane. Proper flashing and air sealing during installation is critical.",
    incentives: ["Current window rebate eligibility should be verified", "Eversource NH Home Energy rebates", "Liberty Utilities programs", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "7–13 years",
  },
  "new-jersey": {
    slug: "new-jersey",
    avgCost: "$300–$680/window",
    avgAnnualSavings: "$150–$320/yr",
    recommendedType: "Double-pane Low-E with argon fill",
    uFactor: "≤0.27",
    climateNote: "New Jersey's mixed climate and high energy costs make Low-E windows cost-effective. NJ Clean Energy Program offers rebates. Coastal NJ homes need moisture-resistant frames. Many older NJ homes have aluminum-frame windows with poor thermal performance.",
    incentives: ["Current window rebate eligibility should be verified", "NJ Home Performance with ENERGY STAR rebates", "JCP&L / PSEG programs", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "8–15 years",
  },
  "new-mexico": {
    slug: "new-mexico",
    avgCost: "$240–$550/window",
    avgAnnualSavings: "$120–$250/yr",
    recommendedType: "Double-pane Low-E with low SHGC for south/west exposures",
    uFactor: "≤0.30",
    climateNote: "New Mexico's high altitude and sunny climate require spectrally selective Low-E glass on south and west exposures. North-facing windows can have higher SHGC to capture passive solar heat. PNM and New Mexico Gas offer rebates.",
    incentives: ["Current window rebate eligibility should be verified", "PNM energy efficiency rebates", "New Mexico Gas Company programs", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "10–18 years",
  },
  "new-york": {
    slug: "new-york",
    avgCost: "$300–$700/window",
    avgAnnualSavings: "$160–$350/yr",
    recommendedType: "Double-pane Low-E with argon fill (triple-pane for upstate NY)",
    uFactor: "≤0.27",
    climateNote: "New York's cold winters and high energy costs make Low-E windows a strong investment. NYSERDA and Con Edison offer rebates. NYC brownstones and older buildings often have historic window requirements — check local codes before replacing. Upstate NY needs higher-performance windows.",
    incentives: ["Current window rebate eligibility should be verified", "NYSERDA Home Performance with ENERGY STAR", "Con Edison / National Grid rebates", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "7–14 years",
  },
  "north-carolina": {
    slug: "north-carolina",
    avgCost: "$240–$540/window",
    avgAnnualSavings: "$120–$250/yr",
    recommendedType: "Double-pane Low-E with argon fill",
    uFactor: "≤0.30",
    climateNote: "North Carolina's mixed climate benefits from Low-E windows year-round. Duke Energy Progress and Duke Energy Carolinas offer rebates. Coastal homes should consider impact-resistant options for hurricane protection.",
    incentives: ["Current window rebate eligibility should be verified", "Duke Energy NC Home Energy rebates", "NCSEA weatherization programs", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "10–18 years",
  },
  "north-dakota": {
    slug: "north-dakota",
    avgCost: "$280–$650/window",
    avgAnnualSavings: "$200–$400/yr",
    recommendedType: "Triple-pane Low-E with argon fill",
    uFactor: "≤0.22",
    climateNote: "North Dakota has one of the coldest climates in the continental US. Triple-pane Low-E with argon (U-factor ≤ 0.22) is strongly recommended. MDU serves most of the state. Wind-driven infiltration around poorly installed windows is a major heat loss source.",
    incentives: ["Current window rebate eligibility should be verified", "MDU Resources energy efficiency programs", "North Dakota WAP weatherization", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "6–11 years",
  },
  ohio: {
    slug: "ohio",
    avgCost: "$260–$580/window",
    avgAnnualSavings: "$140–$300/yr",
    recommendedType: "Double-pane Low-E with argon fill",
    uFactor: "≤0.27",
    climateNote: "Ohio's cold winters and hot summers make Low-E windows a solid investment. AEP Ohio and FirstEnergy offer rebates. Cleveland and Columbus homes often have original aluminum-frame windows from the 1960s–1980s that are major energy drains.",
    incentives: ["Current window rebate eligibility should be verified", "AEP Ohio / FirstEnergy home energy programs", "Ohio Development Services weatherization", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "8–15 years",
  },
  oklahoma: {
    slug: "oklahoma",
    avgCost: "$230–$520/window",
    avgAnnualSavings: "$120–$250/yr",
    recommendedType: "Double-pane Low-E with argon fill",
    uFactor: "≤0.30",
    climateNote: "Oklahoma's hot summers and cold winters require a balance of U-factor and SHGC. Hail and wind are significant risks — impact-resistant glass is worth considering. OG&E and PSO offer rebates for qualifying improvements.",
    incentives: ["Current window rebate eligibility should be verified", "OG&E home energy rebate programs", "PSO efficiency rebates", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "10–18 years",
  },
  oregon: {
    slug: "oregon",
    avgCost: "$260–$580/window",
    avgAnnualSavings: "$130–$280/yr",
    recommendedType: "Double-pane Low-E with argon fill",
    uFactor: "≤0.27",
    climateNote: "Oregon's mild, wet climate means moisture-resistant frames (vinyl, fiberglass) are preferred over wood. Portland area: double-pane Low-E. Eastern Oregon's cold climate benefits from triple-pane. Energy Trust of Oregon offers strong rebates.",
    incentives: ["Current window rebate eligibility should be verified", "Energy Trust of Oregon window rebates (up to $500)", "Pacific Power / Portland General Electric programs", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "8–16 years",
  },
  pennsylvania: {
    slug: "pennsylvania",
    avgCost: "$280–$620/window",
    avgAnnualSavings: "$150–$320/yr",
    recommendedType: "Double-pane Low-E with argon fill",
    uFactor: "≤0.27",
    climateNote: "Pennsylvania's cold winters and humid summers make Low-E argon windows a smart investment. PECO and PPL offer rebates. Philadelphia rowhouses often have no wall cavities, making window replacement the primary envelope improvement option.",
    incentives: ["Current window rebate eligibility should be verified", "PECO/PPL Home Performance with ENERGY STAR", "Peoples Natural Gas weatherization programs", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "8–14 years",
  },
  "rhode-island": {
    slug: "rhode-island",
    avgCost: "$300–$680/window",
    avgAnnualSavings: "$170–$340/yr",
    recommendedType: "Double-pane Low-E with argon fill",
    uFactor: "≤0.27",
    climateNote: "Rhode Island's cold winters and high energy costs make Low-E windows a good investment. National Grid RI offers rebates. Coastal homes need moisture and wind-resistant frames. RI Energy provides comprehensive home energy programs.",
    incentives: ["Current window rebate eligibility should be verified", "National Grid RI Home Energy Savings programs", "RI Energy weatherization rebates", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "7–13 years",
  },
  "south-carolina": {
    slug: "south-carolina",
    avgCost: "$230–$520/window",
    avgAnnualSavings: "$110–$230/yr",
    recommendedType: "Double-pane Low-E with low SHGC (≤0.25)",
    uFactor: "≤0.30",
    climateNote: "South Carolina's hot, humid summers mean low SHGC is the priority. Coastal homes in hurricane-prone areas should consider impact-resistant options. Duke Energy Carolinas and Dominion Energy SC offer rebates for qualifying improvements.",
    incentives: ["Current window rebate eligibility should be verified", "Duke Energy Carolinas home energy programs", "Dominion Energy SC rebates", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "12–20 years",
  },
  "south-dakota": {
    slug: "south-dakota",
    avgCost: "$260–$600/window",
    avgAnnualSavings: "$160–$340/yr",
    recommendedType: "Double-pane Low-E with argon fill (triple-pane recommended)",
    uFactor: "≤0.25",
    climateNote: "South Dakota's cold winters and hot summers create year-round energy savings opportunities. Hail is a significant risk — ask about impact-resistant options. MDU and Xcel Energy offer rebates in select service areas.",
    incentives: ["Current window rebate eligibility should be verified", "MDU Resources energy efficiency programs", "Xcel Energy rebates (select areas)", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "7–13 years",
  },
  tennessee: {
    slug: "tennessee",
    avgCost: "$230–$530/window",
    avgAnnualSavings: "$120–$250/yr",
    recommendedType: "Double-pane Low-E with argon fill",
    uFactor: "≤0.30",
    climateNote: "Tennessee's mixed climate benefits from Low-E windows year-round. TVA EnergyRight offers rebates for qualifying improvements. Nashville and Memphis homes often have older aluminum-frame windows that significantly underperform modern Low-E vinyl.",
    incentives: ["Current window rebate eligibility should be verified", "TVA EnergyRight home energy programs", "Nashville Electric Service programs", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "10–18 years",
  },
  texas: {
    slug: "texas",
    avgCost: "$220–$520/window",
    avgAnnualSavings: "$100–$240/yr",
    recommendedType: "Double-pane Low-E with spectrally selective coating (very low SHGC)",
    uFactor: "≤0.30",
    climateNote: "Texas's extreme summer heat makes solar heat gain control the top priority. Look for SHGC ≤ 0.20 for Dallas, Houston, and San Antonio homes. Oncor, AEP Texas, and CenterPoint offer rebates in select service areas. Impact-resistant glass is recommended in hail-prone North Texas.",
    incentives: ["Current window rebate eligibility should be verified", "Oncor Home Performance rebates", "CenterPoint Energy home improvement programs", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "12–20 years",
  },
  utah: {
    slug: "utah",
    avgCost: "$250–$560/window",
    avgAnnualSavings: "$140–$290/yr",
    recommendedType: "Double-pane Low-E with argon fill",
    uFactor: "≤0.27",
    climateNote: "Utah's cold winters and hot summers make Low-E windows valuable year-round. Rocky Mountain Power offers rebates. Salt Lake Valley's air quality inversion also makes tightly sealed windows important for indoor air quality.",
    incentives: ["Current window rebate eligibility should be verified", "Rocky Mountain Power Home Performance rebates", "Questar Gas home energy programs", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "8–15 years",
  },
  vermont: {
    slug: "vermont",
    avgCost: "$320–$720/window",
    avgAnnualSavings: "$200–$420/yr",
    recommendedType: "Triple-pane Low-E with argon or krypton fill",
    uFactor: "≤0.20",
    climateNote: "Vermont's severe cold makes triple-pane windows one of the best envelope investments. Efficiency Vermont offers rebates and financing. Many older Vermont homes have original single or double-pane windows without Low-E coatings.",
    incentives: ["Current window rebate eligibility should be verified", "Efficiency Vermont Home Energy Loan and rebates", "Green Mountain Power Savings Plan", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "5–10 years",
  },
  virginia: {
    slug: "virginia",
    avgCost: "$260–$580/window",
    avgAnnualSavings: "$130–$270/yr",
    recommendedType: "Double-pane Low-E with argon fill",
    uFactor: "≤0.27",
    climateNote: "Virginia's mixed climate benefits from Low-E windows year-round. Dominion Energy and Appalachian Power offer rebates. Northern Virginia homes near DC often have older aluminum-frame windows. Mountain Virginia (Charlottesville, Roanoke, Appalachia) needs higher-performance windows.",
    incentives: ["Current window rebate eligibility should be verified", "Dominion Energy Home Energy rebates", "Appalachian Power Home Performance programs", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "10–17 years",
  },
  washington: {
    slug: "washington",
    avgCost: "$270–$600/window",
    avgAnnualSavings: "$130–$280/yr",
    recommendedType: "Double-pane Low-E with argon fill",
    uFactor: "≤0.27",
    climateNote: "Western Washington's mild, wet climate means moisture resistance is as important as thermal performance. Vinyl and fiberglass frames are preferred. Eastern Washington's colder, drier climate benefits from triple-pane. Puget Sound Energy and Seattle City Light offer rebates.",
    incentives: ["Current window rebate eligibility should be verified", "Puget Sound Energy / Seattle City Light rebates", "Washington State weatherization programs", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "10–18 years",
  },
  "west-virginia": {
    slug: "west-virginia",
    avgCost: "$250–$570/window",
    avgAnnualSavings: "$150–$310/yr",
    recommendedType: "Double-pane Low-E with argon fill",
    uFactor: "≤0.27",
    climateNote: "West Virginia's mountainous terrain creates cold microclimates that benefit from higher-performance windows. Appalachian Power offers rebates. Many WV homes have older single-pane windows that are major energy drains.",
    incentives: ["Current window rebate eligibility should be verified", "Appalachian Power Home Performance programs", "WV Housing Development Fund weatherization", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "8–14 years",
  },
  wisconsin: {
    slug: "wisconsin",
    avgCost: "$280–$640/window",
    avgAnnualSavings: "$170–$360/yr",
    recommendedType: "Double-pane Low-E with argon fill (triple-pane strongly recommended)",
    uFactor: "≤0.25",
    climateNote: "Wisconsin's harsh winters make triple-pane windows a strong investment. Focus on Energy offers rebates. Madison and Milwaukee homes with older windows often see significant savings from upgrading to triple-pane Low-E.",
    incentives: ["Current window rebate eligibility should be verified", "Focus on Energy Home Performance rebates", "WE Energies / Wisconsin Gas programs", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "7–12 years",
  },
  wyoming: {
    slug: "wyoming",
    avgCost: "$280–$640/window",
    avgAnnualSavings: "$180–$380/yr",
    recommendedType: "Triple-pane Low-E with argon fill",
    uFactor: "≤0.22",
    climateNote: "Wyoming's extreme cold and high winds make triple-pane windows a strong investment. Wind-driven infiltration around poorly installed windows is a major heat loss source. Rocky Mountain Power offers rebates for qualifying improvements.",
    incentives: ["Current window rebate eligibility should be verified", "Rocky Mountain Power Home Performance rebates", "Wyoming Energy Authority programs", "Federal 25C tax credit (verify current IRS rules)"],
    payback: "6–11 years",
  },
}

export function getWindowsStateBySlug(slug: string): WindowsStateData | null {
  return WINDOWS_STATES[slug] ?? null
}

export const WINDOWS_STATE_SLUGS = Object.keys(WINDOWS_STATES)
